import { AppSidebar } from '@/components/app-sidebar';
import { SidebarProvider, SidebarTrigger } from '@/components/ui/sidebar';
import { TooltipProvider } from "@/components/ui/tooltip"
import { cn } from '@/lib/utils';
import { Geist } from 'next/font/google';
import NavHomePageComponents from '../Component/NavHomePageComponents';

const geist = Geist({ subsets: ['latin'], variable: '--font-sans' });

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    
      <div className="h-full w-full  flex flex-col ">
         <div className="sticky top-0 z-20">
          <NavHomePageComponents />
          </div>
     
        <TooltipProvider>
         
        <SidebarProvider>
          <div className="z-50">
          <AppSidebar />
          </div>
          <div className="w-full z-2">
          <main className='w-full '>
            <SidebarTrigger />
           {children}
          </main>
          </div>
        </SidebarProvider></TooltipProvider>
      
      </div>
   
  );
}
