import { AppSidebar } from '@/components/app-sidebar';
import { SidebarProvider, SidebarTrigger } from '@/components/ui/sidebar';
import { TooltipProvider } from "@/components/ui/tooltip"
import { cn } from '@/lib/utils';
import { Geist } from 'next/font/google';
import './globals.css';
import NavHomePageComponents from './Component/NavHomePageComponents';

const geist = Geist({ subsets: ['latin'], variable: '--font-sans' });

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={cn('h-full antialiased font-sans', geist.variable)}>
      <body className="h-full flex flex-col">
        <TooltipProvider>
          <NavHomePageComponents />
        <SidebarProvider>
          <AppSidebar />
          <main>
            <SidebarTrigger />
           {children}
          </main>
        </SidebarProvider></TooltipProvider>
      </body>
    </html>
  );
}
