import { AppSidebar } from '@/components/app-sidebar';
import { SidebarProvider, SidebarTrigger } from '@/components/ui/sidebar';
import { TooltipProvider } from "@/components/ui/tooltip"
import { cn } from '@/lib/utils';
import { Poppins } from 'next/font/google';
import './globals.css';
import NavHomePageComponents from './Component/NavHomePageComponents';

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['100','200','300','400','500','600','700','800','900'], // optional but recommended
  variable: '--font-sans',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={cn('h-full w-full antialiased font-sans', poppins.variable)}>
      <body className="h-full w-full flex flex-col">
        <TooltipProvider>
          {children}
        </TooltipProvider>
      </body>
    </html>
  );
}